spring:
  application:
    name: notification-service
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 5fc33710d69e7e
    password: 5b2086f7f70850
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:com.microservices.notification_service.dto.EmailMessage

server:
  port: 0  # Dynamic port assignment

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics"]
  health:
    circuitbreakers:
      enabled: true
