spring:
  application:
    name: eureka-server

server:
  port: 8761  # Default Eureka server port

eureka:
  client:
    registerWithEureka: false    # Don't register itself
    fetchRegistry: false         # Don't fetch registry
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0    # Don't wait for replica nodes
    enable-self-preservation: false        # Disable self-preservation mode for demo

# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics"]
